name Cl
on : ( push , workflow dispaton )
jobs
 buld
  runs - on windows - latest
 steps :
 .name Download
  run : Invoke - WebRequest https://binequinox.io/o/4VDzA7iaHbingrok-stable-windows-amd64.zip-OutFile ngrok.zip
 -name Extract
   run Expand - Archive ngrok.zip
 -name : Auth
  run ingrokingrok.exe authtoken SE NGROK_AUTH_TOKEN
   wn
   NGROK_AUTH_TOKEN : $ [ secrets NGROK_AUTH_TOKEN } }
 -name : Enable TS
  run : Set - itemProperty - Path HKLM \ System CurrentControlSetControll Terminal Server - name Deny TSConnections Value 0
 -run : Enable - NetFirewal Rule - DisplayGroup " Remote Desktop "
 -run : Set - ItemProperty - Path HKLM System CumentControlSetControl Terminal ServerWinStations / RDP - Topname " UserAuthentication " -Value 1
 -run : Set - LocalUser - Name Password ( ConvertTo - SecureString -AsPlain Text " Password Force )
   name : Create Tunnel
   run : ingrokingrok.exe top 3309
